"""
Synthetic load generator for the todo backend.

============================================================================
Why do this?
============================================================================

Observability dashboards are dull (and learning is harder) when there's no
data flowing. This script POSTs/GETs/PUTs/DELETEs against the backend in
a loop with a deliberate mix of operations and the occasional intentional
error, so:

  - Grafana panels always have lines moving
  - Jaeger always has fresh traces to explore
  - Loki always has new log lines
  - You can see what a "bad" trace looks like (the intentional 4xx errors)

The load is gentle (a few RPS) — this is for learning, not benchmarking.

It's NOT itself instrumented with OpenTelemetry. Keeping it as a plain
client lets you study how the backend looks "from the outside" without
the loadgen's own spans cluttering the picture.
============================================================================
"""

import os
import random
import time
import uuid
from datetime import datetime, timedelta, timezone

import requests

BASE_URL = os.environ.get("BACKEND_URL", "http://backend:5000")
TODOS = f"{BASE_URL}/api/todos"

# Tunables: keep low for local learning, raise to stress test.
RPS = float(os.environ.get("LOADGEN_RPS", "2"))
ERROR_FRACTION = float(os.environ.get("LOADGEN_ERROR_FRACTION", "0.05"))

SAMPLE_TITLES = [
    "Buy groceries",
    "Write OTel blog post",
    "Refactor TodoItem",
    "Call mum",
    "Review PR #42",
    "Plan weekend hike",
    "Stretch",
    "Read chapter 3",
    "Pay credit card",
    "Renew passport",
]


def wait_for_backend():
    """Sit and poll /api/health until the backend is up. Saves us from a
    crash loop while docker-compose brings everything up together."""
    deadline = time.time() + 120
    while time.time() < deadline:
        try:
            r = requests.get(f"{BASE_URL}/api/health", timeout=2)
            if r.status_code == 200:
                print(f"[loadgen] backend ready at {BASE_URL}")
                return
        except requests.RequestException:
            pass
        time.sleep(1)
    raise SystemExit("[loadgen] backend never became ready")


def random_due_date():
    """Half the time give a due date, half the time leave it null. This
    exercises both code paths in the bucketing logic on the frontend
    (and produces more interesting `todo.has_due_date` tag values in
    Jaeger when filtering)."""
    if random.random() < 0.5:
        return None
    offset_days = random.randint(-3, 14)
    when = datetime.now(timezone.utc) + timedelta(days=offset_days)
    return when.replace(microsecond=0).isoformat().replace("+00:00", "Z")


def create_todo(intentional_error: bool = False) -> dict | None:
    """POST a new todo. If intentional_error is set, send an empty title
    so the backend returns 400 — useful for generating error traces."""
    payload = {
        "title": "" if intentional_error else f"{random.choice(SAMPLE_TITLES)} {uuid.uuid4().hex[:4]}",
        "description": "auto-generated by loadgen",
        "due_date": random_due_date(),
    }
    try:
        r = requests.post(TODOS, json=payload, timeout=5)
        if r.status_code == 201:
            return r.json()
        print(f"[loadgen] create non-201: {r.status_code} {r.text[:80]}")
    except requests.RequestException as e:
        print(f"[loadgen] create failed: {e}")
    return None


def list_todos() -> list:
    try:
        r = requests.get(TODOS, timeout=5)
        return r.json() if r.status_code == 200 else []
    except requests.RequestException:
        return []


def complete_todo(todo_id: int):
    """POST to the dedicated /complete endpoint — it toggles, so calling on
    an already-done todo flips it back. The backend only counts false→true
    transitions in the `complete` metric, so this naturally produces a
    mix of "real" completions and no-op flips."""
    try:
        requests.post(f"{TODOS}/{todo_id}/complete", timeout=5)
    except requests.RequestException as e:
        print(f"[loadgen] complete failed: {e}")


def edit_todo(todo_id: int):
    """PUT a genuine field edit (no `completed` toggle). Keeps the generic
    update route exercised so the "Todo operations by type" panel still
    shows an `update` series alongside `complete`."""
    payload = {"description": f"edited by loadgen at {uuid.uuid4().hex[:6]}"}
    try:
        requests.put(f"{TODOS}/{todo_id}", json=payload, timeout=5)
    except requests.RequestException as e:
        print(f"[loadgen] edit failed: {e}")


def delete_todo(todo_id: int):
    try:
        requests.delete(f"{TODOS}/{todo_id}", timeout=5)
    except requests.RequestException as e:
        print(f"[loadgen] delete failed: {e}")


def step():
    """One unit of work. Picks an action with weighted probabilities so
    the request mix looks vaguely like a real user."""
    roll = random.random()
    if roll < ERROR_FRACTION:
        create_todo(intentional_error=True)
    elif roll < 0.55:
        list_todos()
    elif roll < 0.80:
        create_todo()
    else:
        existing = list_todos()
        if not existing:
            create_todo()
            return
        target = random.choice(existing)
        sub = random.random()
        if sub < 0.6:
            complete_todo(target["id"])
        elif sub < 0.85:
            edit_todo(target["id"])
        else:
            delete_todo(target["id"])


def main():
    print(f"[loadgen] starting, target {BASE_URL}, RPS={RPS}, errors~{ERROR_FRACTION*100:.0f}%")
    wait_for_backend()
    interval = 1.0 / max(RPS, 0.1)
    while True:
        try:
            step()
        except Exception as e:
            print(f"[loadgen] step error: {e}")
        time.sleep(interval)


if __name__ == "__main__":
    main()
